---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres14
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.10-12
  primaryUpdateStrategy: unsupervised
  storage:
    size: 50Gi
    storageClass: local-path
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "600"
      max_slot_wal_keep_size: 10GB
      shared_buffers: 512MB
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: https://vdhbackupsa.blob.core.windows.net/cnpg/
      serverName: postgres14 # change/increment when restoring as value cannot match existing cnpg cluster
      azureCredentials:
        connectionString:
          name: cloudnative-pg-secret
          key: azure-connection-string
  # # Note: externalClusters is needed when recovering from an existing cnpg cluster
  # externalClusters:
  #   - name: *previous-cluster
  #     barmanObjectStore:
  #       wal:
  #         compression: bzip2
  #         maxParallel: 8
  #       destinationPath: https://vdhbackupsa.blob.core.windows.net/cnpg/
  #       azureCredentials:
  #         connectionString:
  #           name: cloudnative-pg-secret
  #           key: azure-connection-string
