apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:qn/ZmmDUDBOT/ekIIF7EiLr/vzvChD+eejLY1pSbu+Sz/je7,iv:GFxTTWM+H6dvVioAevHGBjHzj7Fs/j13qTuku54+TQA=,tag:MCLQomgOlFmKt5jV6LaN6g==,type:str]
    credentials.json: ENC[AES256_GCM,data:fSZRUQrg+jHqKZ5PyCrhFJELlEkuXwUM3vPIqWcFNLhl/u17j5w7/uzA/RWUqBL+p9h/6gXx3zns/BtCMrHRE425OtqXdEBbosRIc7mrsaur74RHDpc1XD4YBWAk6acdbNyT+1irfEaSC9nap7q54aMn69po2YDtwCvcYAewGU2pfxnLmiee11uT2KeCah/HL1ETPDHXiWFLKkPYSfbhL/xLcWh4BuRCe4FUbmznEg==,iv:vUQtoGlUSHqYZAVbUFa5KDDKIXhBZi/OWd/PdMip5pk=,tag:SaDo2rymX3CTJQ74aUXWOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbnZOenBTRWpOejhBdkc0
            dUhua0tGS25sNzMwM240b2h4dHdrWWRFakhBCkVPN0lLUmNHMW55M2hjVlR5SnJO
            MHhqWHgyTXdvYlM0NCtnQVM3VlcvS2cKLS0tIEdsZXJtNUMyZ0toSjh0RWV5dmVW
            V3YvQnp0NHFLL3B3T3JHaHRWRVo5U0kKcrsgsLV8V3S/mNOsCjewzP+Cehc4cpts
            IKerGTI818KiFYD7/0+Km6JMhBgxLNPUoFcmRNCR82O55ywoXUc0jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T13:54:03Z"
    mac: ENC[AES256_GCM,data:+zqEbp+EfdcdexRSmbjyz35emXFtUegS41SsyOaDAmzp5aVeIlHUq/ods/LrZ0OTTnTZFgTpu+NaoHT+y09KgoLqNXJ+pgMc4GmJOMc/g78GKBaZOpdzm6jYrmO4G+2ZmtUUTye8jWZCixQ6KvmB25D8yfVxpPMclVgE4XM+2WU=,iv:3EDDjVyq0XvF3GgZhSfott+/NVD+GsES/RMjVUuyQg4=,tag:4bQLrE17Payl8lte23+D6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
