apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:2FgxfThlS+2tbJCF514K+lkmtBaRvdcPu30GwZBCvV+Ee2P9,iv:l0URf/0JJIyjdEwsG/tgda7QALc/IF2cUoTEYZRjeEk=,tag:8Nvb/dN5HjfPS9kVH6ontw==,type:str]
    credentials.json: ENC[AES256_GCM,data:mJBzNpvn+lgtFMLeh/poD0MfQeiqGCLhxosIyc3119vKcTL7iwPLuMxaFwdfoqMuVHlfIz3gSb0WJj8gJtpaNk5IMSl0Ew3xDrbez6jnEQzikczOPjPe7x+kUVS2wdbrJCvMuLjXiqSRBycjQ2vyqD5wsxAQbF0a/7XEAsqldlFSpbpSwgGX/XYPLPL2d4n3evORoRPIpP0EqoJdcG5J4gHCGYlt+tALMN6ceRvaYQ==,iv:QhuGjyCszptGxepWazvKHAPX4gxGY/umsTtiGYTPwUk=,tag:rQEj5msyzjFBblbRSVVgBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUY0ZHTkNoVUJtendqbTVS
            blBqM0ZFdnVTa0MvV2FtOE5oUXFyOXJGVmtBCkd2KzEweStXYUZmTWtaRVdWSEpH
            Z2lPTWdHOWt6eGlxVk9Ua3dYQ25rcDgKLS0tIFRCOUcza1RDanozRmIyUDNwY3NM
            V2lxQVpUUmh5eHowOU9mY09YWVJkTjQKyhXm+LNpz6XmwdONp41RXRBWGDEdAruC
            SJompVej4IWkrKCjw1+V3bnZIGegd/btIyyskvzQrRpI2QMThMTp+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T13:17:04Z"
    mac: ENC[AES256_GCM,data:fUIRmXcNZ1YnsUoZGuz3j39WCWbBCrfVrtWMnyUFHL9zcviVg0UJxILeGd3Qa8V30bL1fnscLd3kHxeLCPZsxe8IO9VMoNq+S4GskVh/bkTa/HxECa9YwqG5zZYwmQJ7eSL6XvskWXsomP2jp1Xo59IqWIjMBPtA1de4tncKvkg=,iv:TLHd8+veeUkl0Iwv3sa6aZlhgo4o6lyhoLojuJfEK7U=,tag:yT07S1HHFvsHfWYO5tUuVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
