apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:FcXLsd296vQHHzMl5qfiC3SOI8JVkE4GAeZ0H2BFnxfawUID,iv:FNPODV18UOJNrB9dLGYWa5iaoYoXfNGzgHQcIOZEwnk=,tag:dpXoT1wCZNVOqljzdeEW1g==,type:str]
    credentials.json: ENC[AES256_GCM,data:CRBB4WpY5jTbgcoqE/Y2ipxV73BLlzpz6BchZYkOXm492ApSNf6lF5+C8XVnZ+fHiecP1dcQjNoaeIQBnNdfzfnrPdovQR2si7F4wccdr01sgo7xXoJ20pkulreEJi9SFHPTGY/USB2wD3/HDY25jrf9ICOFqspMuhyV62vI/MRQv0zLQCjBVRagYJSP7wkPBc6BYSaxZ2V/Km29pR57Ua4qNHHkiWin7muV2AAtfQ==,iv:263wXK7Uo+GlkEk7ZtqDVfEnSg9TC/DMP0TRZKP4pAI=,tag:Xd07OZ0Tr+IJol94m4cvXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VHVXbGp2MDdnTTVCV2pT
            L3IyVkxtUWVOd1J3K3FiVWxMaTNOQjRlQTNrClZ3aHFKazVMcHlQV2dzWXlNZ01o
            NkNhaW1uM0xFVENoNi9qOEY3aHBaYXMKLS0tIDVzZlJGdGpGSzV5V3hDYjVQL3Iz
            Z2Q2N0RwZ3Q5KzRtWEFtbTJzOWNPSHcK2UVaasAF8dZWnk0+MbxtmIFxj/CGUgkh
            ILqNs6FLVuQaZ/wOXBfjhCbAXJY9YPB5YirrjVLsbTWMrhMbD2kZaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T15:31:00Z"
    mac: ENC[AES256_GCM,data:c53r7MnC0VmwaK2ZGvacDQqDzL36CqVsMXiDa2u9Po6x13YHVZALmXVZ4qu6JuW01BpzwTfhdCroFeP7AV3duiKc4CQUvviXLK9HNZTuVTnyrY3qVdiltEqHjFQ+qCsaaMXnKuVqmSbLLWc1ytQlHAU5BVI7+Qeg6r6lciSoNKk=,iv:iVYzf4KVdM9AZPImaQh7jlLk8S2xZ+2GcRgC/6l4y/U=,tag:xtnd5hjB5cyKCq9/j/KWbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
