apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:f0wCo/CVjQeakPN3MqK8D6uuU+6enDkXxYvNtimgulq5iN6c,iv:yxUt+cxpyruJ9s4HQ5t7IU31aJjnjSyEv9Kq7j+ZPlc=,tag:PR4ZukYPizkEHCgVYmTMNQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:P2fuTzOS6qQ0BZuWjiXTW3NW6WxMP6BzxrInmr0cIu/RJ+/5+mlLf9TdZNQqSI5NGenU0DRjXEAaWLwXoxehFMogc0PMg9qc5MMN0+aVgXmaCCCR2VkDlbvKJvZErBR6DFoPCy2T5wn7/+NUKIkf8iqaALWmtl8W0Qo8UY9/Iys6/mVoonI4eOSbkUT8fKLFqemDV8jaVWH+Y2otj4UzVkxFPLklNMz6apsprubFdQ==,iv:LEaXkGIIzMvoq9PBeGznWeJnYDuQ2khhjqIDtmkBrLA=,tag:NrgsrJFrhWch9mUzLImX3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYmFZZjFEUFRMVWc3SFFv
            clp1bmFtY2hHVU5XSmk2NFRxYlhXMlNabTJZCmZZMjIyR3BFZkd5bmxFNFdrcmp6
            My9raEtlOUw3VnpoWmEvWWEvOUtmaFEKLS0tIDNWcVhlYlhlK01lc1NXbm5HTUVV
            SDg1NHVLOFlVSG9uK1Ntc1MvVitmdFEK4MkzPxU6Vx+XsHF5qht2tVdfKZgLkZpD
            lt3PrkN+EW0CC9IC3afIFAwTpSOwtAEjuAN3iBQdTK+0OoJ2INR/Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T11:07:56Z"
    mac: ENC[AES256_GCM,data:Q7bFALappu/0ccJTA2r5+V2PXHO1+w/pyEhOAp6f3EOY+kOoXkzjmMRJqk49/FlpP9N0V5ZXHcNnrK0zCmLIo6fS1iCxj0qZMlw8qphekiOmPSR8A8ON5ovmGQtyZHwczXfpJk9QxEh9zvgzNwO0C7tE3tkbkLDqIsTdTcxI3OE=,iv:3LLSBsDTqrL4+BBJIQv+f7FwOOPzWzzz8gUuIi7aBpA=,tag:KfZlnZ2zO9Wo67VerTnlIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
