apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:sdqNiv1ORzR8K2kd5yzVZcFe9bjdwegMPghyJR31+E0daeoc+011wg==,iv:yjoSrUJjfllnEYmbbE0qobULqWhph8X3WCzFQplKyqU=,tag:vohHWwnuMUcONRsryaQhPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Skl3Q1NPei9RTzVDbk1h
            WW9RdXFScGEzc3hqOFYxaGZsM3VYbkQ0QWdNCkpGS0NYeitBNGJMYmlpTmlZQWcw
            elB1M1c2V0tzSG5VS3djMkRmQU53T1kKLS0tIGZEbWtWTVUwR09sR0MxWHRreCsy
            Sjc3cW9jMG91VWFnUU1TMXVzZVpDbmMKwv91onqa0vUmimajveqCABG+Eem2C3Lr
            7dqOeQiwSIZe9ZEpP6qBXlrzJ/HXJF/CpFW26XkDSBmaKwKE+6uMBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T13:54:03Z"
    mac: ENC[AES256_GCM,data:dBQ3TXGPgdPUCk45zuQL/NbnkJJrLxYWJzHeK8yrWnnwkF6A2c4VZlNSCw5fqsdKT7JDi6z2SZ0KO5Kn0rtEdSKqHeAPTd771aUR8FRtcQwCcJXnzjnb7/qLBvCBOmolt1tiWFeBSmWoAoADP7zSSYscYVJLwxIbp6Cs3Iw2aoI=,iv:7XLRvs0iCmZX7KkdbKht4L/bmOkqHEd4FIr0qsxQT04=,tag:4bt6mP7JCHCtUyHWDj0HUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
