apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:zgZ6OJvzKxsxkruW8ZWOSqAawSFeSTDnB9J2XEBZMzL+dn/rjvs3Qw==,iv:r6IDMngUIHUPMc5pmC08eWKNMqVQC6+bM0aW8LtMjtU=,tag:7o7GKpPU1lxWBiK6QvEjdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdmpxbWhGSXR4N204eHlP
            K0xaaDhxWVRjVE9JRWdOUHFxdnpXR0N6VXlBCmFZeGNBd1ViN2dLZ05tRnFuLzdp
            TWpqRUIwTzVPVkVhWE5iemd5LzVoZm8KLS0tIGZQOUlnaEJIS1FOek9NS3kveWdu
            dnRqcWJRbitmb0UzZ2lBZmI2dzFzTEUKZNt5y8kZLMxvO9mEsnzGmGuX61Nic3tv
            L7pKbsZ9orXGelf04dQmwRRmznIVA1H9LUcGQgnXlq0yafLvkEcWaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T15:31:00Z"
    mac: ENC[AES256_GCM,data:kPkutUxUs9rHNV8qI0pvtTVgxD7HQ6hRd5jZuYncRlNCUkaAcmkj4aYuAJtY2h9bbLJmx3h1er0hvf85OdHq0fjqoltqBG4+Dh31wOxcljU6BUnOaCOLfuN+FIIUP9YDiAgTgDH+bPeR8w6h3+10ENwYYBItYCTp/2aupKgnJZk=,iv:hg62AWjlX2Y+zVL021WSMu3H/bJ3EegVaH9mOM0vTXk=,tag:JNhn24U2uxxsgNR00eMJzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
