apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:BzcA6RtKZjAJHgWKsBAI9xHa48rDR0UpO1hWn0HQ6ryZxQl/dLkboQ==,iv:KX7DXHisg8pc1nQOJEywTEINyDrDkD/Q2EQnqaSTSeE=,tag:CSfQTI9vc5JceSI00GwX1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaVB6WllxbnlObkRUa1JP
            WWdGbUlWNVpka25OZnEzbjdtZDFWRDNsaVJjCmNOajNnSjA4T2g0MDd3TWNUMDdS
            aFF5NCt6VUJUaHl0Wi9OWjVUYlFLNlEKLS0tIGtKVU1oUWFpU3AxWVFidm9TUGMz
            UjloQTcyTURWV1FzVXFEZjVrMVdDZEUKFpfA2F0cZjdRjiotcoX/YF9r4RCo0CDH
            rjD5UyWXAeQ0KHvBeWvfMt18rNfy9M7ckvZs6ct/GIy7RB0VeZDZNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T14:42:17Z"
    mac: ENC[AES256_GCM,data:a3qRer6GkUmfTRImu9F3Nx+Bc/nMasW7AaDjrdPqyYpRtX1ALvh12xO4AaL9J3+TPueO407tFcaYvbTVfx3+MoozxQL7EtpGTdIkxUK2TUfpJ3q5N9K8dyiFfrwjv888cjFkTQ97U7mmbcxNVCLNtJ6opfEv9LNvseNoHiZCQkM=,iv:vWMQ5DfW8lcoZxkmqmrmp281QTBgcdC4YttpG5ME2oM=,tag:CUdpFMyDYx93xo0Y5DNFVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
