apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:G26fjHPx4j4p+1YF1AUIdTIYDnL5BSRqFjoaf12qv5rcvymQI+tmBI/Cc7gok9bb3+6K0nriju2pP9lR2RyPEZQGU5Ya4IKZvrjgYSkmWpvOr//v2zti8lvPA7d2gg==,iv:LDUDyKMvAmVp/Ra8ysbo/Av+sqdKmz2UXFFPxmzyP14=,tag:S9+/t8h62oRHepC/YQij1w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:BSxOzZMaEKyfYvO7TSw=,iv:D4Ee+2ANYs+qM6w4xRTMCkD5jnl1wONcahrYJSZpLl4=,tag:l+r1GgWUPAFIZM84SDxYMw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:FOO2dg/4H0BmnvqXc+ukbL7h1Q==,iv:gtwU8DlFerrbU+giPYFaDdteSQ+xj4axvHReBSuLSos=,tag:oJrs6GNOLMSS+OHQzzPf4g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:qzV8lUhn15tN9/u7zTPFRP9TU3g4ceL6KwhEuUoc8WvofH9g,iv:NbLOzf6RIAhqKBAssOT+GxdjuYvZJ5oKk5mP3sOL/SA=,tag:8mEPnDFLHZVzSACirMqJpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQm5FK242RUFqemwzRVhC
            bGZ0L1RBWHVESXpKUlR4QWpwNEpDeTRTZTFrClVTZzczNHFTZGRkVFNCOXlWOVg2
            SHVMSkdaajBvTVhWU0hYUlhkM2c4ZGMKLS0tIFJXTVR2SXhFZjc1ZVVGWW5ra2FZ
            b3BXWkx0djlvaXE3V1loZHlONEJqVFkK0x1DxEB1ir2ET8eoaIOyrF3ajSFmZQhI
            8uoAA1t/2TJQ2fiHVQRZOubxnZugJlyqtAd90fUoCRcE8F8GNBzY6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T19:01:13Z"
    mac: ENC[AES256_GCM,data:mqrYTYmfeyNx1jbRDKR+lHWfDXH7v8qa+YoAD3exsI5Tox+NsF4Dk0FL17DV9qKqZH2WPXZuVjkMvhBP7w75PUbpx2b2NvRDtGVBXwzACYNEALQ1HLWymsHhoXPDZeJUaMOhago8jrGohABAnXm9kmMrcH4UQwFBFThSsqjOJ6U=,iv:svAdHWbcREHfcWxAqm6UuklnMbcdcHAAyA4e0jov2RY=,tag:uCa+u0wzaiki6ntZta52uA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
