apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:4WmjUPoXWxW5sQt7SXqj6eoMeYNEuEjc0EcCGcvMtKCLD76wqAptwmzv0n8Rc6V2DusGUWfA8qXt/mp0+XdQckjDjnFxamUfvoEHKj/PHazAUY/nrYL/aIZrrth0pw==,iv:XmK6yuR5pH6rCveKrpLe6l0rhEyKUZ6g6edRYqn0rNk=,tag:GCYOk/8n192x7ExgkrTmAQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7j+gsBRzQ5xwRvtMFoA=,iv:d2DybzeKf1/Eg1FjokljqVRqxt1ZbSZT7Eqv13P+IY0=,tag:5wPUN7Vu80J0HgzB5R7PRw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ew1vmTOvF3A5G1BLR+DI4Mfkrw==,iv:mcJNkGG/FToE/lBJjDpCn6XEHvYV3XcP05y05EGiOBg=,tag:dckPKT3CmP+mOpF6U2uROA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ZZ6I/mfQS/JBHEla7dwH97eNwK92Gd5+xfv27qi1rmtpvbiG,iv:W0HTpW3YwBdIKkfaWJigZjntepr8+P1ZOtnPGiixmAg=,tag:So1IK9hBQbsiIMU4xCDuXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRS9lM09rRHlTamF6b3oy
            Qk5vU2pYZXFJUXJTOEk1eUlLTU1SV09NMDE0CkZWRHJ2RDNON2hxdm5RRjdsUjhU
            U29IVWxYeGRTSllWbnAxM3AxbjVYb2sKLS0tIDgzWU50NFd1RjJKMG5Ma0ZwVU5m
            L2JRUHBTRUhOTXNnb1Y3ZTRkNVRObk0KjASUisej40w9G5YJC53H/5JNNKFdI+dZ
            Kmf5wjxxL7YSK2AzYmaCH6UgRxCfi9d8q/qtXiV6t9y0ysnFhYHw6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T11:07:56Z"
    mac: ENC[AES256_GCM,data:rssGysuZIqBuO7PljHUwhvOTUpuqDJE9MS0/NCJWHDZywSplh84FrTSyuuU1RGu/oheMRe8pWz+u+FwSUX06AOAPjDUdwdZeIfBoJxu8E9QuQz+VIkeKXDzgUYpMSKPiOp5GaTVFFQr8S1bWZ9dZZSNhdu/qd3PUbbd2RCl4i/I=,iv:+sxchlEonbGw0KtrMHpuPoHB5EjKBDyRiFUWfDHXcvk=,tag:RLXi6a1lLbpJJR8levu/5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
