apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:o10dpjluu0axyTw9OasdRT9r8uUBVv2d8CsjiriNUc/13lgAKFgQCMiZU1NIGzizbfqDVXrlpktEG3vBIqnMA9zijm0XVThcxPPzp9Dd4J+tajCHmw/R/4U9spxGWg==,iv:4K0Xt9yPDpEHQmLcirbML9ctHAIgXdc+CrtCtSsv68g=,tag:9NtyscZdEP9Yvh/1nghcXA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:kV8tOlLyPy54LZis6YU=,iv:FX4xMCl+I+Ax6U7O6pwWkzGSWp0TtTBfaMgXzLZkivs=,tag:1adsJocSHoPYUmWyFGATwA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:LaQBvcpIgKBsTnRNKKiYOuNkVA==,iv:QMLBfgjhKPsIqXqPp0XgtM3D4Cy/7cW+03R3Qf51xU4=,tag:50E76w5c9Jh4S7NEdbOpGw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:NiA17xxWWc/nZ5ZwA4dsCdAgxvgiDVs9UHZQzsnZ+Z1Njftg,iv:pGWsNkrD+hSfOLWsh8G9XUCkN6H18U/6xfMViN0XbxE=,tag:E7wfvq9jo1hbZ2+4eYVAsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN1B3M1lrMW84NDRsdGJx
            WHg1UzR5NU5WTzVDaFJ4SWkrbFUzZjd3YTEwCkNpYWVMVTVrMWdsWW1WKzlWODY1
            bCt0bmRDWjNZbTdkNXB6RkZMU3lQc28KLS0tIGI4L0E0UE1XcjRub2NBckJoamVm
            VFgrd084dUR6cC9BQXV6QUFPVUVORE0K+DjY2v85ETs5OqXxygmj6GfDdphtJgWI
            vHADqjg0NHnUmmgxw/Kv5baxnB6V7EmYmJb1JDReuizReqf2F4amNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T18:23:29Z"
    mac: ENC[AES256_GCM,data:y/R29xi3Vb4iwBfQA36NeoPCYaWuHDoWPI1J+mmiKCKMYJy44GevPkpuroRSK9sZxmT0ijBEegMFB3olpWSSQTZT2Vb+ax3PWg6DdtWT7S95p8aZUz4gBYKLhtKr2LynDoh7fcEN6/KRFBuErRXCphyTigG3pmfiVlTy+9JjRQs=,iv:wrYmhUAXOBv5uY+KP22c6VXCfVPEms4d1oJ6Iml8BW8=,tag:LAasJjJPdeNHT+JWiYZu6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
