apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:mf40XIVaUzGJSuuoam0nunySLRvHYc7DGLVBZhg8mkgaFKS6o3/BKp1cgl+xhr8J0FHcG7SBLjM/ywlxoZAtM7w98DsjWslg29dQ2QeGvy1vngfo+CR0PkY/9JdQ4g==,iv:y+HeKbxdNCImOSWN1jYE6KooQ/EukeJeqSblKOXA9to=,tag:Hu/rqbtVjLF7OhktmeTegw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:wF9hiNoPPtZqVqVlLGo=,iv:XSfROAPMlAzAezSyTiUZ3IzhiyF2CPbJkcKOnol4Cb0=,tag:7Lth1Xbhs16yKvU4BVD/0g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:s0BF/8uR8IoydudxfsHPOPVOzw==,iv:V4J3B2vfwMBAxvEaAFLEdiUof8Dl4fzwtT5yrOSmUVA=,tag:woLYbtMjSFruescZFrbaaA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:jUyYtSt2cJEKo9oBrVrVF/A5NWZ8pi3J+LR19y3Iy7ox3rY3,iv:B+/atcdZgXiSvtwdUmYZ+7g9701riU2zjS/gsbAHN7g=,tag:tmrIEh0y9r1uMpCps+pXHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcDhvK01HQ2RZYlJyc28v
            SlA1T2RHU01YTEdPY1VKcjVGcXhSdkh0RkRBCkw1Rmx2bHBQOTZqbGhzYnJlaDRr
            QTBUZ3lUY0dCSUJZSkJrU2RZb2t5VFkKLS0tIE90alVNTVNxNlliK0xxcWJwU3ho
            SndJclFySURLdjVJVXhmQ0FHQ1pyVEkKOgeHZwF2dv1pRq1cHkZMPU4hBkiOdzpw
            S2RkMDka+uG4t8dqmXfUty7eGS8au3jJ3akEgM1zY7bBvgUQhC/KOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T14:42:17Z"
    mac: ENC[AES256_GCM,data:RB09ETsAweiZDqtEjiPZo4FeAF7Mcu55aNDHQMPCTq1wD3/JSIvonhp7hRXUVUzTI7puMUxhSNO2DGqeiDAUfbCOXN/cVPp+nbTnZ7xqMTxyGfvurRorHyR4d7RaFT2MXU1zst7IA6dvp0LVOnl0TQWrK5J7dpOg/C1zuY3cuxU=,iv:slq4o90mZDJS43G4G16bKDesHZK0W0hXpPivZpj7aqg=,tag:9UoS/hLhevIvlTOuzGUIvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
