apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:01XdivK0Z2PDYCov+up1J1Ap2glmsv4igWhq8TOwc4tMotbDuY4Q9SeKeNKUpsL1LQE4snEhShMeo/Ix8JXdMDBkj8OjApr+2HZrripFAGg/uoBPHRZdTIndd1DxQA==,iv:cyMSH6iMkDBlSYH/3odOVzwdIOT54nroxk/zm0RlM+w=,tag:+9h8jbLj/ahLkIw6GlWAqA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:SFvPYDBpZ5h1B7NsJgk=,iv:zfE7pOhBVH947Dayn3HwWtX7w/g8phvxpkEQqb1qlTM=,tag:nh3n+PX6bWZpoqNsHuI1/g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:l0qf4C3TwJAkZuO5VQPQx68/MQ==,iv:RdAHbLWY0yK8un6qeelJRInKxgw9P9SgCrQvkpKBdR0=,tag:IB331oHAeD/OkULUyXkE2w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:7T5YMDOCHpydFO+K6G6BTwc2/Is/Hs+bWxjvzae3BP0igNnT,iv:Pyz6jx9HHONYQwpTENp8G1+nETm1jSO9cQubBpKlZZI=,tag:tVE7TXKEhEQ/zD4gO/5Hyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbmJZVTVtdGxVNlZNa1Nv
            YUNzcEhCc2lJSHdoUFVyR2tvczlOMHB0ZGtRCjF4eTFESkhXMWFucUFjamVCU2dv
            VU42WUNWNWVGMnBJWDlUS2VFMXB5Tk0KLS0tIFI5VlJZczN0OVRtYzdnVWNNeHBF
            bzNxRmZxdzNFalBxR3JCQVpsTzd2cVEK8USV54S2Yl0Y0LwALEoXOOdkZUE1m0fH
            o5r600sp2ejV5yOY0b+xSfmbPFmRlYB9+Jg6TouCsI5J2osSQWnMrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T14:24:00Z"
    mac: ENC[AES256_GCM,data:sOKYyhKKn6TIPQ5q6AI3HFb/nDUpt3DOKikqsdx08uQc8Qurz5O+6yWuswz4f/nMos67qu48j0hGuAMPgCUuAqSdBs9lcqCtAk5eBxgTtS+0FyBkMjiybl3m4LPhLEsGZ7rqKsXNC7mVcZTyYgZPRgKhDo0u787UDA/Hi8mPSNs=,iv:wE6MWBSm1dDFCWy5F3jPrmIGPpUlDAyHb4iExFIypZ0=,tag:NFcqEIYEO/MWymY2ZpPxsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
