apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:wD1a0vB+LXjhTivwBGuiPtgFWLBkPaMEDutaGB+vN9e0RtFphWlmi7BlSHhZg8VxrHZ9vlx2rPzkBpS2v/hRbu3JdhvqDNGO+vPbUd9evxQv1Hyw/TgRL5nMQIuqDA==,iv:uceWsWfKzNluSrk+mOk2QHUEQInTwytPDHdscv1eTjk=,tag:ePGln4pJjhcgSM8BJOC2KQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:DHxw53g3LLneKkSxl7A=,iv:aFAqPC7fbkLTqlG83+gvNe19zN3GU/dQXDdKcr+PtSs=,tag:UF5h/lW0XA/csioGnmsCtw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:+MjYdEfi4E9D5NxIWeGMvkXrzA==,iv:aUr8r00vTB2uURULF+kUoASVxuDrLBoh784plAWBDWg=,tag:0/LHm3aMcFEb7iSi4E509Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:9HqsoF6n+JgIq13IzYsCvNlGLh6v8pzkhhdRBQRKUsyRNzmA,iv:4vucxWo+SNd13Jaerdsxw6Ui+W1Dcwsx3qgv4gCsvyE=,tag:1eUppa5+0cPXxdgv5eXh1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmR2VVMXdsSDlFamlaNTd3
            TXJCb2prOE12M3I2NkEreHhNL0FJK1RSTG1FCkhibnIwUWtCT2VVYkZGMVlVK3pC
            ZTJXdjlpMWUzckNUYU96SkMwSFJoVGMKLS0tIHFRSnM2dGE5YmRacmkxTG43SURk
            d0FRRis2VkFJeXFZU1NUUzNMUGlySlkKgiyC9kgiHGqD9qsU3doDs2xkVvceZTb2
            aNzvlbkZHkualxPqF4mZ5QEhSmcqjZJyZbDoQuGC3MHJSGRNLIz/pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T16:34:17Z"
    mac: ENC[AES256_GCM,data:PVkRMBLoP8kIN4xLRFwlGZR7miYdDsQrSHlaewY+0PBcwIHYOaiRoPB7QmyO/iBJrQo5YXTIslS/nZyx/j/PPoqT+cxeZdZLN4WHPRuZr28CJ3bWAjsRVN2GkiMrPOBDGJvwBlp5OohmJQo7uWFSwhADjyD1SKNSWfXdIJI4D+4=,iv:g2ElNBqb0TBj6ypxdHgJ2jJkxQIu8OTDvkmyl9/R0R4=,tag:8CWqVX8Ro4sLd8Qpv2WjBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
