apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:tQQbG0lsUt7OONLYnro4vAeXKjV0vGOxSNlapcljjJE=,iv:htuoWCd9iq1HY5i3uGpF9RzoaQtvz0AqbB+XRGPHon0=,tag:HIlZNX+ZOzrMiipQUmyYwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTkdrWlRxeC82WU1vaSto
            U2syZFpyMzhVdDNaWm9NM3p1Zkt0N0lnU2xBCnVYaUczd3NWTEx5d2FNcU1uQkJk
            bDNGVmNId0FObHF1YkRIVW15V0lBM1UKLS0tIHNLbWVPY3hNZlhtblRKUDZLdVNq
            clFpelpEb2JVZEl5Wm85TE1XSm9RWGMKEg60aNRCzWmNBO6IiutDKcYsIABthghD
            87jm20sVQ/4S3yvwD1r+aVYiirXCQ1nf6vF39hcC6COmnyWCVT5iJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T16:11:43Z"
    mac: ENC[AES256_GCM,data:7yH32VoaVH37ElhCKuQkv6UkZm8WQbwghaewJiyddoGGgQoYtMw+hRBcffe6flQTqDUC81xnm+hTX4mhRcPnt4uJ82X9eEcwlv3R6Dw0AY5X8HEQMrD4tawpAuMrGIJJuJJ4U/6SC2NnC8kssYZBmyU5BHlEPp8Iwc0MnLWa0r8=,iv:bijpqSq5VhkvQehnIdYG3e5RDZnVoPV28BafAGwKtZ8=,tag:aaRpfD8HY5ldJ12zNcA/Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
