apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:/FGHf4U+2OHzuegrU5NlUXOBpZlZ015dISQcs8QkU2w=,iv:QdQibIIrxCI3pThUkng3bwn98Uq5sNXsz6iy+Dzt7Mc=,tag:BnWEbvIlkUXVl0/Jlbz9ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZDRjWi9KMzAvWER6SlBy
            MlY1WEFnUHVDRkN2aDZEdW82MFMxZXFqOFRvCjdTdnhiVGN4S0lGa3Mzc1RRRWc1
            WEcwc0hIMXVnNmFHQnNYUjdjZUVUWHMKLS0tIDdqcTc0eEFRd1lLNGZZdjBLdlI3
            WnJMUzBSOHNzcTFrNTRxM3F5MGd0Um8KeS+CXpiePXLdJlv/c6vUFHioXtdtbCZE
            3pw2VW3TYT3mSuytSOJ4ldS141FwANYc1Asd1CKTPe603vf0J46xng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T18:23:29Z"
    mac: ENC[AES256_GCM,data:uRAnlGdFVOxl9myWwd7Wzm/c8Klf5s4rjZtrH8uYD9SOa0bgXTSRyHh1auINEDzl9/JGNu3pIOCpFv0srww/O4NEn5i4wycDZ2lMy9OoO0qix/7xZzfSY/FUZ6i8O4FaB6+zUYWEcm7he7QOzzv9AnZ6qTFsRzpLste2UqeGRJk=,iv:jy2N7LOr41/AAyBizOGsTbdKzgkgv7Kspc1aEUpWkV4=,tag:hAJxqnpEA4PRiZmRocOMSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
