apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:bQy+W+CgJHT5RWLk7dWBxaNXKXy/ACJudQx5S43pJak=,iv:FJVhU/6gQUZlJYiyd56uLcuOXFoNL1SXVkumC1LOXME=,tag:va+Wq4YglQ3MqzP1/lD9Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib1Y1SW1HbS9FeHhTU2Q3
            WkVKUHVjTmdXR0xmRHlqeVlaU3U1M2dCZmc0CnpQK1c3c0dmSDZnMnNOZTZxc0Ry
            cWd6ZldaMUF4Ui9ZNkdJbDR5QUdrVHcKLS0tIGN0c09PbDIzNmJZMkJTSGdhbmpi
            MTc3YVcxem1kdDZVdmIwblNmZ0JvakkKgyG/mQVRwoGfPZlYndiOG8u9U60L9d/o
            EZfZJD9f4f4Iy9yFWiVp8LD3LrBO7xSKk3vUBoHE9Nje7w7n39GSZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T14:44:39Z"
    mac: ENC[AES256_GCM,data:7PMq5HhGugQAyt0pUih1Ddo7/IEFJf/4INCae8soIU/f4BvU/6TuAcEzirf39y8d+vEjHBglEkPP14awy5ekDfZ64UeI0QoL/vAh2o4+6TF7sT0UZMTkLeqyPaduJSsKBND+IJh67T0wXSGk1776YB46Vyy42Tz1CdJ8CYIRr44=,iv:Ra4MggZzi4iZUGdqTNaZFFUbP2Larcj/MRJZ7/g4xoU=,tag:3SjdSDFA6LFQ2ur7ZWhlOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
