apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4OSr50OCeUQ0FILsczAuQKVIfxNzVTlNO0AwW74rTUnkCT9Lx1HlLQ==,iv:LjAwXrMylnDVTnwreOsA4XvVkEYP8cN7YepPpJYaFRs=,tag:vHTViZcTO1pK5eES5lDQAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGT2dhemRSY29vK1F0R2dJ
            ZGdJenlISEk2K0Iyb1psZ2EwZTQzQXliaVJ3CndwQVVDY1ZWdlQwYUhkK0YyVmw3
            Y1gxNkpUZFlENlNXK21lTXczd3UxWFUKLS0tIGE2Mkl3MUVMTVJwZzJXdm15d0NY
            MjlYWC8veTFwOHpmaHJyelRqdWJzSlEKtzJsvya9nP3owh6BQmYqx/hsf8p1+Wm9
            h8eSppswkEVRZvffOIZBX7uBEn3JESkAJS5epQMQDb0w/ybDueraAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T12:06:26Z"
    mac: ENC[AES256_GCM,data:zSd1iXLZUI43TP9/AHQ40nx8cuphbUS5Ee/dNFCj/E7tVbsPnHAkI0JUD8q/16NLxaiMf1vEvnDthKRQd30N1HG7rKb8tKRFcMX9aVp6vqe/rNG4kbBFRCOc4UGm/EKIKbxeZsXh3uJN8+WWm7lb8+8K/7kR5Wlw6I2vr1fCwfE=,iv:+Sj6wvZDj/rJNanE4JmejLCSyxeiRJGVtAJlDr+8kss=,tag:igepBGs3F6JOhKUe8aKkww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
