apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:UK3KNEZrcQQqa1tGKg6IMoYr5qiHYkfUaNIEIsl4NmwSBRjyiBfREw==,iv:q4wnFZdFVoZjQ9Qp2WsAu9Zu8kqd+uLK0Rgzl8YMncA=,tag:bSMXuHOEhXoWRxsZMVbPUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbnc3ODRwODZTMUlrWWU4
            clk1MjRscjFFaUdEV1M5eSs1VXA2RC8rZ0EwCllKN0c4NHdpUDROc2s1a2hKQkV5
            TDhVS0NuWEtHb1lkN0x1QW1aRXo0bTgKLS0tIFNncWlUWERqaUpjdUhtZS9iQ1lt
            VlRDY1JvVjY3OGdJYzcvNEN4LzNQWUEKnur6dXbohiKkW1oKaBPLjc24STUcMgN5
            06fiq2EJEs3vJjSYRLq3SleJErDCPPwa41YaHvVWLZheW3yHYJbgPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T18:23:29Z"
    mac: ENC[AES256_GCM,data:CNLgEyDjuONySYdzozJU7D4z2FG0jTAtoeXSf4hGze9jjZBwr5NrQkm027ue1XerRVxaJId2ihkmIVzx5Bph08jwHD0Q/Gn7xrgszKqXVUHVO++cjgzIHVtRoyIuMgKJCBLFTQas2NkgNtvgfa352yfhmFq24AVfkBxLfFNnu04=,iv:B6UsIGDMHuF03oCb9YqJD83ThogrKikqc1cFYDyhXjQ=,tag:PAimKv2pRI/50i9+nxiQ8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
