apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:QKhv4L5yxD/DLuy0S9M630IGhpSOOSq77Db1jNCWoUYzbKisEIbWhA==,iv:DIi0WhQ742THHlArQd7WGxnQzHozprs6phoDKwTkO9I=,tag:1A634cSM8M5GYV1HnMIKcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdnRuY1hNN3ZrQ1lENU1v
            TFAzRkZhS2ovcDRHVnVLYU9nbklYcmVTQ3dVCm12anVCU3o0Tll1cEU0OTVJZTEy
            Z0xzTkxFVXF1UFRJV0o4TEUrOE9JVTAKLS0tIFhsMmcxM09sa2pwYmZvbjd2VlVF
            N2ZuOWh0S1pLOTFLTVRhU0dvbWJNQWMKUWvpmfVi00ZNzeZxMDXvemZexzO3alfv
            sRR3p7Zv88Easi/4hitHIiWYUorv2Q/r9BIvevWsH0/4SqRdJkYZ/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T13:00:32Z"
    mac: ENC[AES256_GCM,data:KzReRXRZZYkTq+h7xWxJiOhT40MjVeIooH4/il1KV1To1yOJRP4j1/9AB4/Vzq+ZL0yirnlTYVGD8W/XbVcD2BczfV57MGFqHiGIFWtVVpWzmLIiNgxDrmFJrfbT628p8UlC9kANAyefw5knuHk4+CoqhJj0WwrQ/u4adlpuoPc=,iv:GTzueh6JKqx5aiLjaPJPHX6BTzCOAuAIFTETXpQvuw4=,tag:X99HdmpXXyftcZ/KHQCmbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
