apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Y1o8XgO/CP3Qcxcj0Pc6LWfGqFrUNqvt2IBAueRBh6LUsqAp8mjuIQ==,iv:tKpSl+16lsK+gXMn9L20++M26+Gy2G8fnFornpYLFTM=,tag:4rO/EhfqGMu2CRN6eigxGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNFFpSjJ6L1AwaldqZDg4
            WXdMcFdLdlYvdXcyU2thWDNLU0hPMlJRNEFVCjVROUkyYnl1N0YrWlNkcTJwYnNH
            SUUwekwyekZrT3drRExnMm5LQmUxZVEKLS0tIHBpOWhVRVRmOXp4N09ycUxGUldv
            WHBJZ3BNU3JrT3h3MDFNSGdqZ0NqaHMKuJULf1Qr9gbEAlQcNF7el8d1ZS2hbLzC
            TSxhwdvzoWruhBjOPiYUE+Xswl9oelqSLaIyjcLptlQTta1V3ooi/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T21:17:10Z"
    mac: ENC[AES256_GCM,data:+0hxYGBbAiMsLajubVvH38MwiBpvnrtRzW2/IVMYpGY/c5qvt9tDE1PXphVrEkk5U9P5t5awt4+k5KtmCuMiBZcqi7B7XMEDbIVF4qjhunAdndAHjUF/dPqFyO2tiTCkGFaMl43L2OWbVE9V0pZKr8G7BjcRJfc1Z+VtZXqh5es=,iv:aUjz9h8grKwymKQGwhdb4lrzBzlwuIsOvG3nYHPvz4Y=,tag:P4LHxGjzaBYc9GufIPBAtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
