apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:zUloouKtNN3swG3YdQplXKcjQei2idjieFFP7yBPMjhya+kiWhBp2A==,iv:sKjhdpDp6yHhKQnr1NtqzwUrmDkCvNBOajjjHPszrmY=,tag:Dg1wN1iQ/npWgTs7I6ECRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ejdxS3N5N3Z0a3kyS25i
            SEZFelFnU0htNlhoVVIza0MvbDY1NHZsZFYwCnZuRHBhdm5TemZpL0JvbGp1NUhX
            aGNOTFo5OFBtVFArOXBZVWpQVG1IQVEKLS0tIEFXZjlKNXltU3ZvSFdKdjJsSTRs
            djJnbXdHdUptSkhrTVBucjlvRCtlUWcKZ35QjTTaMH6n8zB53Yow6AJmprfEAx+e
            ZxAPHoDmpujr03opXp6xPApaGcZEzy2MHyrvmR72P7KQSJOHzlK5Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T13:30:11Z"
    mac: ENC[AES256_GCM,data:5GR2cuTQZ8KwREhIH3xGtFSzIda8LzQLTb7VCli3CKrCBNG44JAtWyiyeOfYx7jfA0JJV9LlKY7jSd78rMoL4/UMBZfur0YhmEwSHMSf6Yuwd2usfsqFvgf5AMAaovRk2IAPRZCiYf089tjmNmSiwKu55ulktrkz+KX63SWmoes=,iv:zH5HzKwrUd2FXRQVUqFIWjgTLbiGYUHVXrw/l4u+mXw=,tag:27x0z6QzkM5FPTyyjledaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
