apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:gaH1Mdf9/UgGhJSe4q9nXfSl+E9xfx/u6G30y64+iz/p8s/hKOvazw==,iv:r+/gdjZpKu4zKBszUjAZdm9xUk5Y3Y170DGbnNUghaE=,tag:EKol5iLwM8SKkYYAio9JGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV2lIbnpzSmFWajVJMW9G
            OUczV3o1bklOQXNHTmVXcjFSRm5weFpESjBjCmhrZCthVmMyVG9FTWtZOUo1ZStG
            UE5JSG1QNDNJQk9Bc0p3RFBLZmw1TzgKLS0tIGVNb1BZQVA2WkU0UGs0ZUVHeDhG
            ZDRUOTI4emROdU0rRFVNVTNrR1cycU0KOCjjIvP+FLq6PtGO+p2kT3IWXv+4LtfD
            dOB49CPBkCBcvKEx0XpeO1snW69Zq2JL0R3KlIt270YI2uuIQuGQhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T19:01:12Z"
    mac: ENC[AES256_GCM,data:XpCnV2jfuP7mX3S1w2VIyem3QMnHy1zrs5WevxJHWSwL9qJoAV0BzW4CfVU8BYGpbtRvziLYOk0yy+iAVrHHvdHv5HpyD9NZYVoS/0gRroKeHWAAwgL1dY8XZlAsO73GOPz5j2dODydQIJ78gKxCPUISxJr/6n3vfmWridcgLZU=,iv:3MCXlPCIzbiQWZPCTbovdI5JE1zFMC5Nz2I7JmPmIc4=,tag:fCFZURYQQGTqd/Q8ARbcmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
