apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:AGD5J32F0HyaAbsgq303J7Rz3ZEPy1B2EVIn50XOciqyL/KOLsJorQ==,iv:3IVRMu4+NlcrmZLbq/ubim59ePL2xbfxL9sYEKc+dpc=,tag:lCbcddT7E5ck6x6d/hk2Jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQ2ZCZjI0dTBDOEJJUnA2
            RWx2OSs5RjYvS0RUQ3Zzams0c1NvNjV0U21nCjVEYjEwdHo1eGxDK2lUME1uVjVW
            M2NFNnRBK2dMNDBKdVArbVV6eGR4QlUKLS0tIGUxZzB5dFVNZkF4Qk1peWVBTDBM
            K3JjV1ozdXZ6SFQ1YnZwQmQzYjJCUVUKyaP5BHG00RKwA+/9qeLFdM0YtxZTjSRw
            32i/e/abHwDQBOiReZm6/AzlQkQ7YPXQCkGRclOn1o6AJHt+NLtfzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T14:37:27Z"
    mac: ENC[AES256_GCM,data:Jkklh9+K56j7CM3M/RjNgqqMhPUT4FesBF8dJ4qMA9Qo7R2GHgsD+xYQDCUMTH+loxPJ+aKofVTZVWXde9Ekhk7SeaTWduvOJjfYocrWq4CmJNdDMBuyDaqqT0piUt+ekRRvYQcTfrzEcpr3BCToe8P7cFs9a266UsBetAg23kg=,iv:1gFqDJIVisQTlK81gG++GJQX8CH4Haba07XAAKuYjPY=,tag:dCWq1WDqqd2kq+HgwnrmhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
