apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:+2H4Z9G6F5mb4a4362I4KKjNNjZHq07DU9kD2rwyV/fsIqE5gJCFrA==,iv:WXE84kjf3LNAIuQqq0VXSFy8p1aKuBGsaJznYMTaL+Y=,tag:tLzDSe6ZPG6IZfeSc5PINg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qf6gmrz0gmddj789hycaq6ftnanussae87pa9l8jdn297c02pxsqcrppv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN3BvV2xlcUVudjZDZ2cx
            SVFKTHdEdm9MZUcydy9nL0dxeXp0bjU0NmdjCjgvSUIwQXdTdkpBZVRzdnU5blpY
            TXlWN1pENTVtYTdib3JTZHhoR3d2V1UKLS0tIERPT1dNOEhYZFM4QzlNdE1XUmtF
            MDRzUGZYTmt4c0hpOG1LYzZXREZiWTAKvB1pKXrXPT76lAQnuaj11Lx9S/7ROmAy
            4r0iT/rHEQkSHRblGsXUNXs9MymViev8KclHOeC1t+rncaL59fKR9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T13:54:03Z"
    mac: ENC[AES256_GCM,data:6Uh9WIcykxQ9yYjpyHG0NS7pbavE3golbOywjyOm8xyXhzomNcpHWmoUXxMz4JdOcx2RQXdgkd+234JE/5FDdK1GsfeLV9G7+j7369K1PCxZCPiikORbMBrVR0FfREX86O0tlfX68eYWGwsTEhTzVumQVi9Y0bQtyk3dXQDdoo4=,iv:CyQMtgWhZ8Lud2sJJ2sIhqquyftIY9N3rkMFP8Hbu9Q=,tag:YtlKYsl+gwy8CEPvbJRVmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
